2020-11-07 11:07:04,759 - ERROR - my_log.py - 34 - test error
